# docker-compose.yml

version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: app_data
        target: /app/app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev

volumes:
  app_data: